// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sparse.proto

package sparseblock

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrgBlockDetailsProto struct {
	OrgBlockNumber       uint64   `protobuf:"varint,1,opt,name=OrgBlockNumber,proto3" json:"OrgBlockNumber,omitempty"`
	Authpath             []byte   `protobuf:"bytes,2,opt,name=Authpath,proto3" json:"Authpath,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	TxnIndexList         []uint64 `protobuf:"varint,4,rep,packed,name=TxnIndexList,proto3" json:"TxnIndexList,omitempty"`
	PrevioushHash        []byte   `protobuf:"bytes,5,opt,name=PrevioushHash,proto3" json:"PrevioushHash,omitempty"`
	PrevFatblockNumber   uint64   `protobuf:"varint,6,opt,name=PrevFatblockNumber,proto3" json:"PrevFatblockNumber,omitempty"`
	LastConfigBlockNum   uint64   `protobuf:"varint,7,opt,name=LastConfigBlockNum,proto3" json:"LastConfigBlockNum,omitempty"`
	MetadataSignature    []byte   `protobuf:"bytes,8,opt,name=MetadataSignature,proto3" json:"MetadataSignature,omitempty"`
	MetadataLastConfig   []byte   `protobuf:"bytes,9,opt,name=MetadataLastConfig,proto3" json:"MetadataLastConfig,omitempty"`
	SparseBlockFilter    []byte   `protobuf:"bytes,10,opt,name=SparseBlockFilter,proto3" json:"SparseBlockFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgBlockDetailsProto) Reset()         { *m = OrgBlockDetailsProto{} }
func (m *OrgBlockDetailsProto) String() string { return proto.CompactTextString(m) }
func (*OrgBlockDetailsProto) ProtoMessage()    {}
func (*OrgBlockDetailsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{0}
}

func (m *OrgBlockDetailsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgBlockDetailsProto.Unmarshal(m, b)
}

func (m *OrgBlockDetailsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgBlockDetailsProto.Marshal(b, m, deterministic)
}

func (m *OrgBlockDetailsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgBlockDetailsProto.Merge(m, src)
}

func (m *OrgBlockDetailsProto) XXX_Size() int {
	return xxx_messageInfo_OrgBlockDetailsProto.Size(m)
}

func (m *OrgBlockDetailsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgBlockDetailsProto.DiscardUnknown(m)
}

var xxx_messageInfo_OrgBlockDetailsProto proto.InternalMessageInfo

func (m *OrgBlockDetailsProto) GetOrgBlockNumber() uint64 {
	if m != nil {
		return m.OrgBlockNumber
	}
	return 0
}

func (m *OrgBlockDetailsProto) GetAuthpath() []byte {
	if m != nil {
		return m.Authpath
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetTxnIndexList() []uint64 {
	if m != nil {
		return m.TxnIndexList
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetPrevioushHash() []byte {
	if m != nil {
		return m.PrevioushHash
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetPrevFatblockNumber() uint64 {
	if m != nil {
		return m.PrevFatblockNumber
	}
	return 0
}

func (m *OrgBlockDetailsProto) GetLastConfigBlockNum() uint64 {
	if m != nil {
		return m.LastConfigBlockNum
	}
	return 0
}

func (m *OrgBlockDetailsProto) GetMetadataSignature() []byte {
	if m != nil {
		return m.MetadataSignature
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetMetadataLastConfig() []byte {
	if m != nil {
		return m.MetadataLastConfig
	}
	return nil
}

func (m *OrgBlockDetailsProto) GetSparseBlockFilter() []byte {
	if m != nil {
		return m.SparseBlockFilter
	}
	return nil
}

type LastBlockMappingProto struct {
	LastOrgBlockNum      uint64   `protobuf:"varint,1,opt,name=LastOrgBlockNum,proto3" json:"LastOrgBlockNum,omitempty"`
	LastOrgBlockHash     []byte   `protobuf:"bytes,2,opt,name=LastOrgBlockHash,proto3" json:"LastOrgBlockHash,omitempty"`
	SourceFatBlockNum    uint64   `protobuf:"varint,3,opt,name=SourceFatBlockNum,proto3" json:"SourceFatBlockNum,omitempty"`
	LastConfigBlockNum   uint64   `protobuf:"varint,4,opt,name=LastConfigBlockNum,proto3" json:"LastConfigBlockNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockMappingProto) Reset()         { *m = LastBlockMappingProto{} }
func (m *LastBlockMappingProto) String() string { return proto.CompactTextString(m) }
func (*LastBlockMappingProto) ProtoMessage()    {}
func (*LastBlockMappingProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{1}
}

func (m *LastBlockMappingProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockMappingProto.Unmarshal(m, b)
}

func (m *LastBlockMappingProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockMappingProto.Marshal(b, m, deterministic)
}

func (m *LastBlockMappingProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockMappingProto.Merge(m, src)
}

func (m *LastBlockMappingProto) XXX_Size() int {
	return xxx_messageInfo_LastBlockMappingProto.Size(m)
}

func (m *LastBlockMappingProto) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockMappingProto.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockMappingProto proto.InternalMessageInfo

func (m *LastBlockMappingProto) GetLastOrgBlockNum() uint64 {
	if m != nil {
		return m.LastOrgBlockNum
	}
	return 0
}

func (m *LastBlockMappingProto) GetLastOrgBlockHash() []byte {
	if m != nil {
		return m.LastOrgBlockHash
	}
	return nil
}

func (m *LastBlockMappingProto) GetSourceFatBlockNum() uint64 {
	if m != nil {
		return m.SourceFatBlockNum
	}
	return 0
}

func (m *LastBlockMappingProto) GetLastConfigBlockNum() uint64 {
	if m != nil {
		return m.LastConfigBlockNum
	}
	return 0
}

type ChannelHeadInfoProto struct {
	LastFatBlockNumberProcessed uint64                            `protobuf:"varint,1,opt,name=LastFatBlockNumberProcessed,proto3" json:"LastFatBlockNumberProcessed,omitempty"`
	OrgHeadPostion              map[string]*LastBlockMappingProto `protobuf:"bytes,2,rep,name=OrgHeadPostion,proto3" json:"OrgHeadPostion,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral        struct{}                          `json:"-"`
	XXX_unrecognized            []byte                            `json:"-"`
	XXX_sizecache               int32                             `json:"-"`
}

func (m *ChannelHeadInfoProto) Reset()         { *m = ChannelHeadInfoProto{} }
func (m *ChannelHeadInfoProto) String() string { return proto.CompactTextString(m) }
func (*ChannelHeadInfoProto) ProtoMessage()    {}
func (*ChannelHeadInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{2}
}

func (m *ChannelHeadInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelHeadInfoProto.Unmarshal(m, b)
}

func (m *ChannelHeadInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelHeadInfoProto.Marshal(b, m, deterministic)
}

func (m *ChannelHeadInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelHeadInfoProto.Merge(m, src)
}

func (m *ChannelHeadInfoProto) XXX_Size() int {
	return xxx_messageInfo_ChannelHeadInfoProto.Size(m)
}

func (m *ChannelHeadInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelHeadInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelHeadInfoProto proto.InternalMessageInfo

func (m *ChannelHeadInfoProto) GetLastFatBlockNumberProcessed() uint64 {
	if m != nil {
		return m.LastFatBlockNumberProcessed
	}
	return 0
}

func (m *ChannelHeadInfoProto) GetOrgHeadPostion() map[string]*LastBlockMappingProto {
	if m != nil {
		return m.OrgHeadPostion
	}
	return nil
}

type FatBlockMerkleInfoProto struct {
	MerkleRoot           []byte                           `protobuf:"bytes,1,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	OrgHashMap           map[string]*OrgBlockDetailsProto `protobuf:"bytes,2,rep,name=OrgHashMap,proto3" json:"OrgHashMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *FatBlockMerkleInfoProto) Reset()         { *m = FatBlockMerkleInfoProto{} }
func (m *FatBlockMerkleInfoProto) String() string { return proto.CompactTextString(m) }
func (*FatBlockMerkleInfoProto) ProtoMessage()    {}
func (*FatBlockMerkleInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{3}
}

func (m *FatBlockMerkleInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FatBlockMerkleInfoProto.Unmarshal(m, b)
}

func (m *FatBlockMerkleInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FatBlockMerkleInfoProto.Marshal(b, m, deterministic)
}

func (m *FatBlockMerkleInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FatBlockMerkleInfoProto.Merge(m, src)
}

func (m *FatBlockMerkleInfoProto) XXX_Size() int {
	return xxx_messageInfo_FatBlockMerkleInfoProto.Size(m)
}

func (m *FatBlockMerkleInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FatBlockMerkleInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_FatBlockMerkleInfoProto proto.InternalMessageInfo

func (m *FatBlockMerkleInfoProto) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *FatBlockMerkleInfoProto) GetOrgHashMap() map[string]*OrgBlockDetailsProto {
	if m != nil {
		return m.OrgHashMap
	}
	return nil
}

type TxnInfoProto struct {
	IndexInFatBlock      uint64   `protobuf:"varint,1,opt,name=IndexInFatBlock,proto3" json:"IndexInFatBlock,omitempty"`
	TxnMVCCStatus        int32    `protobuf:"varint,2,opt,name=TxnMVCCStatus,proto3" json:"TxnMVCCStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnInfoProto) Reset()         { *m = TxnInfoProto{} }
func (m *TxnInfoProto) String() string { return proto.CompactTextString(m) }
func (*TxnInfoProto) ProtoMessage()    {}
func (*TxnInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{4}
}

func (m *TxnInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnInfoProto.Unmarshal(m, b)
}

func (m *TxnInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnInfoProto.Marshal(b, m, deterministic)
}

func (m *TxnInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnInfoProto.Merge(m, src)
}

func (m *TxnInfoProto) XXX_Size() int {
	return xxx_messageInfo_TxnInfoProto.Size(m)
}

func (m *TxnInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_TxnInfoProto proto.InternalMessageInfo

func (m *TxnInfoProto) GetIndexInFatBlock() uint64 {
	if m != nil {
		return m.IndexInFatBlock
	}
	return 0
}

func (m *TxnInfoProto) GetTxnMVCCStatus() int32 {
	if m != nil {
		return m.TxnMVCCStatus
	}
	return 0
}

type SparseTxnFilterProto struct {
	FatBlockNumber       uint64          `protobuf:"varint,1,opt,name=FatBlockNumber,proto3" json:"FatBlockNumber,omitempty"`
	TxnInfoList          []*TxnInfoProto `protobuf:"bytes,2,rep,name=TxnInfoList,proto3" json:"TxnInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SparseTxnFilterProto) Reset()         { *m = SparseTxnFilterProto{} }
func (m *SparseTxnFilterProto) String() string { return proto.CompactTextString(m) }
func (*SparseTxnFilterProto) ProtoMessage()    {}
func (*SparseTxnFilterProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c442573753a956c7, []int{5}
}

func (m *SparseTxnFilterProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SparseTxnFilterProto.Unmarshal(m, b)
}

func (m *SparseTxnFilterProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SparseTxnFilterProto.Marshal(b, m, deterministic)
}

func (m *SparseTxnFilterProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SparseTxnFilterProto.Merge(m, src)
}

func (m *SparseTxnFilterProto) XXX_Size() int {
	return xxx_messageInfo_SparseTxnFilterProto.Size(m)
}

func (m *SparseTxnFilterProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SparseTxnFilterProto.DiscardUnknown(m)
}

var xxx_messageInfo_SparseTxnFilterProto proto.InternalMessageInfo

func (m *SparseTxnFilterProto) GetFatBlockNumber() uint64 {
	if m != nil {
		return m.FatBlockNumber
	}
	return 0
}

func (m *SparseTxnFilterProto) GetTxnInfoList() []*TxnInfoProto {
	if m != nil {
		return m.TxnInfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*OrgBlockDetailsProto)(nil), "sparseblock.OrgBlockDetailsProto")
	proto.RegisterType((*LastBlockMappingProto)(nil), "sparseblock.LastBlockMappingProto")
	proto.RegisterType((*ChannelHeadInfoProto)(nil), "sparseblock.ChannelHeadInfoProto")
	proto.RegisterMapType((map[string]*LastBlockMappingProto)(nil), "sparseblock.ChannelHeadInfoProto.OrgHeadPostionEntry")
	proto.RegisterType((*FatBlockMerkleInfoProto)(nil), "sparseblock.FatBlockMerkleInfoProto")
	proto.RegisterMapType((map[string]*OrgBlockDetailsProto)(nil), "sparseblock.FatBlockMerkleInfoProto.OrgHashMapEntry")
	proto.RegisterType((*TxnInfoProto)(nil), "sparseblock.TxnInfoProto")
	proto.RegisterType((*SparseTxnFilterProto)(nil), "sparseblock.SparseTxnFilterProto")
}

func init() { proto.RegisterFile("sparse.proto", fileDescriptor_c442573753a956c7) }

var fileDescriptor_c442573753a956c7 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0x56, 0x9a, 0x6e, 0xff, 0x76, 0xda, 0x9f, 0x0d, 0x33, 0x44, 0x18, 0x12, 0x2a, 0x11, 0x42,
	0x11, 0x42, 0xa9, 0xd8, 0x40, 0x4c, 0x70, 0x03, 0x2b, 0x4c, 0x9b, 0xb4, 0x42, 0x95, 0x55, 0x5c,
	0x20, 0x81, 0x70, 0x52, 0xaf, 0x89, 0x96, 0xda, 0x91, 0xed, 0x4c, 0x9d, 0x78, 0x17, 0xae, 0x78,
	0x1b, 0x9e, 0x86, 0x37, 0x40, 0xb6, 0x9b, 0x36, 0x69, 0x53, 0xee, 0xe2, 0xef, 0x1c, 0x7f, 0xe7,
	0xfb, 0xce, 0x71, 0x0e, 0xb4, 0x45, 0x86, 0xb9, 0x20, 0x7e, 0xc6, 0x99, 0x64, 0xa8, 0x65, 0x4e,
	0x61, 0xca, 0xa2, 0x2b, 0xf7, 0x97, 0x0d, 0x7b, 0x9f, 0xf8, 0xf8, 0x58, 0x1d, 0xde, 0x13, 0x89,
	0x93, 0x54, 0x0c, 0x74, 0xd6, 0x13, 0xb8, 0x55, 0xe0, 0x1f, 0xf3, 0x49, 0x48, 0xb8, 0x63, 0x75,
	0x2c, 0xaf, 0x19, 0x2c, 0xa1, 0x68, 0x1f, 0xb6, 0xde, 0xe5, 0x32, 0xce, 0xb0, 0x8c, 0x9d, 0x46,
	0xc7, 0xf2, 0xda, 0xc1, 0xfc, 0x8c, 0x10, 0x34, 0x4f, 0xb1, 0x88, 0x1d, 0x5b, 0xe3, 0xfa, 0x1b,
	0xb9, 0xd0, 0x1e, 0x4e, 0xe9, 0x19, 0x1d, 0x91, 0xe9, 0x79, 0x22, 0xa4, 0xd3, 0xec, 0xd8, 0x5e,
	0x33, 0xa8, 0x60, 0xe8, 0x31, 0xfc, 0x3f, 0xe0, 0xe4, 0x3a, 0x61, 0xb9, 0x88, 0x35, 0xc1, 0x86,
	0x26, 0xa8, 0x82, 0xc8, 0x07, 0xa4, 0x80, 0x13, 0x2c, 0xc3, 0x92, 0xca, 0x4d, 0xad, 0xb2, 0x26,
	0xa2, 0xf2, 0xcf, 0xb1, 0x90, 0x3d, 0x46, 0x2f, 0x93, 0xb9, 0x05, 0xe7, 0x3f, 0x93, 0xbf, 0x1a,
	0x41, 0xcf, 0xe0, 0x76, 0x9f, 0x48, 0x3c, 0xc2, 0x12, 0x5f, 0x24, 0x63, 0x8a, 0x65, 0xce, 0x89,
	0xb3, 0xa5, 0x95, 0xac, 0x06, 0x14, 0x7b, 0x01, 0x2e, 0xb8, 0x9c, 0x6d, 0x9d, 0x5e, 0x13, 0x51,
	0xec, 0x17, 0x7a, 0x0e, 0xba, 0xde, 0x49, 0x92, 0x4a, 0xc2, 0x1d, 0x30, 0xec, 0x2b, 0x01, 0xf7,
	0xb7, 0x05, 0x77, 0xd5, 0x65, 0x8d, 0xf5, 0x71, 0x96, 0x25, 0x74, 0x6c, 0xe6, 0xe4, 0xc1, 0x8e,
	0x0a, 0x94, 0xa6, 0x32, 0x1b, 0xd4, 0x32, 0x8c, 0x9e, 0xc2, 0x6e, 0x19, 0xd2, 0x8d, 0x35, 0x13,
	0x5b, 0xc1, 0xb5, 0x3a, 0x96, 0xf3, 0x88, 0x9c, 0x60, 0x39, 0xe7, 0xb5, 0x35, 0xef, 0x6a, 0x60,
	0x4d, 0x67, 0x9b, 0xeb, 0x3a, 0xeb, 0xfe, 0x6c, 0xc0, 0x5e, 0x2f, 0xc6, 0x94, 0x92, 0xf4, 0x94,
	0xe0, 0xd1, 0x19, 0xbd, 0x64, 0xc6, 0xcc, 0x5b, 0x78, 0xa0, 0xd2, 0x4b, 0xdc, 0x21, 0xe1, 0x03,
	0xce, 0x22, 0x22, 0x04, 0x19, 0xcd, 0x8c, 0xfd, 0x2b, 0x05, 0x7d, 0xd5, 0xcf, 0x56, 0xb1, 0x0e,
	0x98, 0x90, 0x09, 0xa3, 0x4e, 0xa3, 0x63, 0x7b, 0xad, 0x83, 0x97, 0x7e, 0xe9, 0xd5, 0xfb, 0x75,
	0xc5, 0xfd, 0xea, 0xbd, 0x0f, 0x54, 0xf2, 0x9b, 0x60, 0x89, 0x6c, 0x9f, 0xc0, 0x9d, 0x9a, 0x34,
	0xb4, 0x0b, 0xf6, 0x15, 0xb9, 0xd1, 0xfa, 0xb6, 0x03, 0xf5, 0x89, 0x8e, 0x60, 0xe3, 0x1a, 0xa7,
	0x39, 0xd1, 0x1d, 0x6e, 0x1d, 0xb8, 0x95, 0xf2, 0xb5, 0x93, 0x0c, 0xcc, 0x85, 0xd7, 0x8d, 0x23,
	0xcb, 0xfd, 0x63, 0xc1, 0xbd, 0xc2, 0x61, 0x9f, 0xf0, 0xab, 0x94, 0x2c, 0x7a, 0xf4, 0x10, 0xc0,
	0x40, 0x01, 0x63, 0x52, 0x97, 0x6c, 0x07, 0x25, 0x04, 0x0d, 0x01, 0x94, 0x44, 0x2c, 0xe2, 0x3e,
	0xce, 0x66, 0xee, 0x5f, 0x54, 0xca, 0xaf, 0x61, 0xf6, 0x17, 0xd7, 0x8c, 0xf9, 0x12, 0xcf, 0xfe,
	0x77, 0xd8, 0x59, 0x0a, 0xd7, 0x98, 0x7e, 0x55, 0x35, 0xfd, 0xa8, 0x52, 0xb5, 0x6e, 0xcb, 0x94,
	0x3d, 0x7f, 0x9b, 0x2d, 0x86, 0xc2, 0xa7, 0x07, 0x3b, 0x7a, 0x23, 0x9c, 0xd1, 0x42, 0x6f, 0xf1,
	0xb0, 0x97, 0x60, 0xb5, 0x2e, 0x86, 0x53, 0xda, 0xff, 0xdc, 0xeb, 0x5d, 0x48, 0x2c, 0x73, 0xa1,
	0xcb, 0x6f, 0x04, 0x55, 0xd0, 0xfd, 0x01, 0x7b, 0xe6, 0xbf, 0x1a, 0x4e, 0xa9, 0xf9, 0xab, 0xe6,
	0x8b, 0xae, 0xfa, 0x98, 0x8a, 0x45, 0x57, 0x45, 0xd1, 0x1b, 0x68, 0xcd, 0xf4, 0xe9, 0xbd, 0x65,
	0x1a, 0x7b, 0xbf, 0x62, 0xb1, 0xac, 0x3f, 0x28, 0x67, 0x1f, 0x1f, 0x7e, 0x79, 0x3e, 0x4e, 0x64,
	0x9c, 0x87, 0x7e, 0xc4, 0x26, 0xdd, 0xf8, 0x26, 0x23, 0x3c, 0x25, 0xa3, 0x31, 0xe1, 0xdd, 0x4b,
	0x1c, 0xf2, 0x24, 0xea, 0x46, 0x6c, 0x32, 0x61, 0xb4, 0x5b, 0x62, 0x13, 0xe1, 0xa6, 0xde, 0xd7,
	0x87, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xcc, 0x90, 0x25, 0xbf, 0x05, 0x00, 0x00,
}
