// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/cluster.proto

package orderer

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	common "github.com/hyperledger/fabric-protos-go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitRequestType int32

const (
	SubmitRequestType_ENVELOPE SubmitRequestType = 0
	SubmitRequestType_BLOCK    SubmitRequestType = 1
	SubmitRequestType_BATCHES  SubmitRequestType = 2
)

var SubmitRequestType_name = map[int32]string{
	0: "ENVELOPE",
	1: "BLOCK",
	2: "BATCHES",
}

var SubmitRequestType_value = map[string]int32{
	"ENVELOPE": 0,
	"BLOCK":    1,
	"BATCHES":  2,
}

func (x SubmitRequestType) String() string {
	return proto.EnumName(SubmitRequestType_name, int32(x))
}

func (SubmitRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{0}
}

// StepRequest wraps a message that is sent to a cluster member.
type StepRequest struct {
	// Types that are valid to be assigned to Payload:
	//
	//	*StepRequest_ConsensusRequest
	//	*StepRequest_SubmitRequest
	//	*StepRequest_SubmitPayload
	Payload              isStepRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StepRequest) Reset()         { *m = StepRequest{} }
func (m *StepRequest) String() string { return proto.CompactTextString(m) }
func (*StepRequest) ProtoMessage()    {}
func (*StepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{0}
}

func (m *StepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepRequest.Unmarshal(m, b)
}

func (m *StepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepRequest.Marshal(b, m, deterministic)
}

func (m *StepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepRequest.Merge(m, src)
}

func (m *StepRequest) XXX_Size() int {
	return xxx_messageInfo_StepRequest.Size(m)
}

func (m *StepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepRequest proto.InternalMessageInfo

type isStepRequest_Payload interface {
	isStepRequest_Payload()
}

type StepRequest_ConsensusRequest struct {
	ConsensusRequest *ConsensusRequest `protobuf:"bytes,1,opt,name=consensus_request,json=consensusRequest,proto3,oneof"`
}

type StepRequest_SubmitRequest struct {
	SubmitRequest *SubmitRequest `protobuf:"bytes,2,opt,name=submit_request,json=submitRequest,proto3,oneof"`
}

type StepRequest_SubmitPayload struct {
	SubmitPayload *SubmitPayload `protobuf:"bytes,3,opt,name=submit_payload,json=submitPayload,proto3,oneof"`
}

func (*StepRequest_ConsensusRequest) isStepRequest_Payload() {}

func (*StepRequest_SubmitRequest) isStepRequest_Payload() {}

func (*StepRequest_SubmitPayload) isStepRequest_Payload() {}

func (m *StepRequest) GetPayload() isStepRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepRequest) GetConsensusRequest() *ConsensusRequest {
	if x, ok := m.GetPayload().(*StepRequest_ConsensusRequest); ok {
		return x.ConsensusRequest
	}
	return nil
}

func (m *StepRequest) GetSubmitRequest() *SubmitRequest {
	if x, ok := m.GetPayload().(*StepRequest_SubmitRequest); ok {
		return x.SubmitRequest
	}
	return nil
}

func (m *StepRequest) GetSubmitPayload() *SubmitPayload {
	if x, ok := m.GetPayload().(*StepRequest_SubmitPayload); ok {
		return x.SubmitPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepRequest_ConsensusRequest)(nil),
		(*StepRequest_SubmitRequest)(nil),
		(*StepRequest_SubmitPayload)(nil),
	}
}

// StepResponse is a message received from a cluster member.
type StepResponse struct {
	// Types that are valid to be assigned to Payload:
	//
	//	*StepResponse_SubmitRes
	Payload              isStepResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StepResponse) Reset()         { *m = StepResponse{} }
func (m *StepResponse) String() string { return proto.CompactTextString(m) }
func (*StepResponse) ProtoMessage()    {}
func (*StepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{1}
}

func (m *StepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResponse.Unmarshal(m, b)
}

func (m *StepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResponse.Marshal(b, m, deterministic)
}

func (m *StepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResponse.Merge(m, src)
}

func (m *StepResponse) XXX_Size() int {
	return xxx_messageInfo_StepResponse.Size(m)
}

func (m *StepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepResponse proto.InternalMessageInfo

type isStepResponse_Payload interface {
	isStepResponse_Payload()
}

type StepResponse_SubmitRes struct {
	SubmitRes *SubmitResponse `protobuf:"bytes,1,opt,name=submit_res,json=submitRes,proto3,oneof"`
}

func (*StepResponse_SubmitRes) isStepResponse_Payload() {}

func (m *StepResponse) GetPayload() isStepResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StepResponse) GetSubmitRes() *SubmitResponse {
	if x, ok := m.GetPayload().(*StepResponse_SubmitRes); ok {
		return x.SubmitRes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepResponse_SubmitRes)(nil),
	}
}

// ConsensusRequest is a consensus specific message sent to a cluster member.
type ConsensusRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusRequest) Reset()         { *m = ConsensusRequest{} }
func (m *ConsensusRequest) String() string { return proto.CompactTextString(m) }
func (*ConsensusRequest) ProtoMessage()    {}
func (*ConsensusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{2}
}

func (m *ConsensusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusRequest.Unmarshal(m, b)
}

func (m *ConsensusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusRequest.Marshal(b, m, deterministic)
}

func (m *ConsensusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusRequest.Merge(m, src)
}

func (m *ConsensusRequest) XXX_Size() int {
	return xxx_messageInfo_ConsensusRequest.Size(m)
}

func (m *ConsensusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusRequest proto.InternalMessageInfo

func (m *ConsensusRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ConsensusRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ConsensusRequest) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// SubmitRequest wraps a transaction to be sent for ordering.
type SubmitRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// last_validation_seq denotes the last
	// configuration sequence at which the
	// sender validated this message.
	LastValidationSeq uint64 `protobuf:"varint,2,opt,name=last_validation_seq,json=lastValidationSeq,proto3" json:"last_validation_seq,omitempty"`
	// content is the fabric transaction
	// that is forwarded to the cluster member.
	Payload *common.Envelope `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// passing blocks
	IsConfig             bool              `protobuf:"varint,4,opt,name=isConfig,proto3" json:"isConfig,omitempty"`
	Type                 SubmitRequestType `protobuf:"varint,5,opt,name=type,proto3,enum=orderer.SubmitRequestType" json:"type,omitempty"`
	Block                *common.Block     `protobuf:"bytes,6,opt,name=block,proto3" json:"block,omitempty"`
	Batches              []*Batch          `protobuf:"bytes,7,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{3}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}

func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}

func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}

func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}

func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SubmitRequest) GetLastValidationSeq() uint64 {
	if m != nil {
		return m.LastValidationSeq
	}
	return 0
}

func (m *SubmitRequest) GetPayload() *common.Envelope {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SubmitRequest) GetIsConfig() bool {
	if m != nil {
		return m.IsConfig
	}
	return false
}

func (m *SubmitRequest) GetType() SubmitRequestType {
	if m != nil {
		return m.Type
	}
	return SubmitRequestType_ENVELOPE
}

func (m *SubmitRequest) GetBlock() *common.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SubmitRequest) GetBatches() []*Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

// SubmitResponse returns a success
// or failure status to the sender.
type SubmitResponse struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Status code, which may be used to programatically respond to success/failure.
	Status common.Status `protobuf:"varint,2,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	// Info string which may contain additional information about the returned status.
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitResponse) Reset()         { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()    {}
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{4}
}

func (m *SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResponse.Unmarshal(m, b)
}

func (m *SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResponse.Marshal(b, m, deterministic)
}

func (m *SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResponse.Merge(m, src)
}

func (m *SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitResponse.Size(m)
}

func (m *SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResponse proto.InternalMessageInfo

func (m *SubmitResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SubmitResponse) GetStatus() common.Status {
	if m != nil {
		return m.Status
	}
	return common.Status_UNKNOWN
}

func (m *SubmitResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type Batch struct {
	Reqs                 []*SubmitRequest `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{5}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}

func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}

func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}

func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}

func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetReqs() []*SubmitRequest {
	if m != nil {
		return m.Reqs
	}
	return nil
}

// SubmitPayload wraps a transaction to be sent for ordering.
type SubmitPayload struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// last_validation_seq denotes the last
	// configuration sequence at which the
	// sender validated this message.
	LastValidationSeq uint64 `protobuf:"varint,2,opt,name=last_validation_seq,json=lastValidationSeq,proto3" json:"last_validation_seq,omitempty"`
	// content is the fabric transaction
	// that is forwarded to the cluster member.
	Payload              *common.Envelope `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TxnId                string           `protobuf:"bytes,4,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SubmitPayload) Reset()         { *m = SubmitPayload{} }
func (m *SubmitPayload) String() string { return proto.CompactTextString(m) }
func (*SubmitPayload) ProtoMessage()    {}
func (*SubmitPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b50707fd3a71f2, []int{6}
}

func (m *SubmitPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitPayload.Unmarshal(m, b)
}

func (m *SubmitPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitPayload.Marshal(b, m, deterministic)
}

func (m *SubmitPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitPayload.Merge(m, src)
}

func (m *SubmitPayload) XXX_Size() int {
	return xxx_messageInfo_SubmitPayload.Size(m)
}

func (m *SubmitPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitPayload proto.InternalMessageInfo

func (m *SubmitPayload) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SubmitPayload) GetLastValidationSeq() uint64 {
	if m != nil {
		return m.LastValidationSeq
	}
	return 0
}

func (m *SubmitPayload) GetPayload() *common.Envelope {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SubmitPayload) GetTxnId() string {
	if m != nil {
		return m.TxnId
	}
	return ""
}

func init() {
	proto.RegisterEnum("orderer.SubmitRequestType", SubmitRequestType_name, SubmitRequestType_value)
	proto.RegisterType((*StepRequest)(nil), "orderer.StepRequest")
	proto.RegisterType((*StepResponse)(nil), "orderer.StepResponse")
	proto.RegisterType((*ConsensusRequest)(nil), "orderer.ConsensusRequest")
	proto.RegisterType((*SubmitRequest)(nil), "orderer.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "orderer.SubmitResponse")
	proto.RegisterType((*Batch)(nil), "orderer.batch")
	proto.RegisterType((*SubmitPayload)(nil), "orderer.SubmitPayload")
}

func init() { proto.RegisterFile("orderer/cluster.proto", fileDescriptor_e3b50707fd3a71f2) }

var fileDescriptor_e3b50707fd3a71f2 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x8d, 0x13, 0xc0, 0x61, 0x20, 0x88, 0x6c, 0xbe, 0x7c, 0x75, 0x39, 0x21, 0xaa, 0x56, 0x56,
	0xa4, 0xd8, 0x15, 0x39, 0xb4, 0x3d, 0x55, 0x35, 0x42, 0xa2, 0x6a, 0xd4, 0x44, 0xeb, 0x28, 0xaa,
	0x7a, 0x41, 0x6b, 0x7b, 0x01, 0xab, 0xc6, 0x6b, 0xbc, 0xeb, 0x28, 0xfc, 0x97, 0x1e, 0xfa, 0xe3,
	0xfa, 0x43, 0x2a, 0xef, 0xda, 0x86, 0x90, 0x34, 0xd7, 0x9e, 0x60, 0xdf, 0x9b, 0x7d, 0x33, 0xf3,
	0x66, 0xbc, 0x70, 0xca, 0xd2, 0x80, 0xa6, 0x34, 0xb5, 0xfd, 0x28, 0xe3, 0x82, 0xa6, 0x56, 0x92,
	0x32, 0xc1, 0x90, 0x5e, 0xc0, 0xbd, 0x13, 0x9f, 0x2d, 0x97, 0x2c, 0xb6, 0xd5, 0x8f, 0x62, 0x07,
	0xbf, 0x35, 0x68, 0xb9, 0x82, 0x26, 0x98, 0xae, 0x32, 0xca, 0x05, 0x9a, 0xc0, 0xb1, 0xcf, 0x62,
	0x4e, 0x63, 0x9e, 0xf1, 0x69, 0xaa, 0x40, 0x43, 0xeb, 0x6b, 0x66, 0x6b, 0xf8, 0xd2, 0x2a, 0x94,
	0xac, 0x51, 0x19, 0x51, 0xdc, 0x9a, 0xec, 0xe1, 0xae, 0xbf, 0x83, 0xa1, 0x8f, 0xd0, 0xe1, 0x99,
	0xb7, 0x0c, 0x45, 0x25, 0xb3, 0x2f, 0x65, 0xfe, 0xaf, 0x64, 0x5c, 0x49, 0x6f, 0x34, 0x8e, 0xf8,
	0x36, 0xb0, 0x25, 0x90, 0x90, 0x75, 0xc4, 0x48, 0x60, 0x1c, 0x3c, 0x29, 0x70, 0xad, 0xd8, 0x8d,
	0x40, 0x01, 0x38, 0x4d, 0xd0, 0x8b, 0x9b, 0x03, 0x17, 0xda, 0xaa, 0x4b, 0x9e, 0xe4, 0x75, 0xa2,
	0xf7, 0x00, 0x55, 0x71, 0xbc, 0xe8, 0xef, 0xc5, 0xa3, 0xc2, 0x54, 0xf0, 0x64, 0x0f, 0x37, 0xcb,
	0xca, 0xf8, 0xb6, 0xa8, 0x07, 0xdd, 0x5d, 0x27, 0x90, 0x01, 0xba, 0xbf, 0x20, 0x71, 0x4c, 0x23,
	0xa9, 0xda, 0xc4, 0xe5, 0x31, 0x67, 0xca, 0x3e, 0x72, 0x23, 0xda, 0xb8, 0x3c, 0xa2, 0x1e, 0x1c,
	0x2e, 0xa9, 0x20, 0x01, 0x11, 0x44, 0xb6, 0xd8, 0xc6, 0xd5, 0x79, 0xf0, 0x6b, 0x1f, 0x8e, 0x1e,
	0xf8, 0xf4, 0x4c, 0x06, 0x0b, 0x4e, 0x22, 0xc2, 0xc5, 0xf4, 0x8e, 0x44, 0x61, 0x40, 0x44, 0xc8,
	0xe2, 0x29, 0xa7, 0x2b, 0x99, 0xad, 0x86, 0x8f, 0x73, 0xea, 0xb6, 0x62, 0x5c, 0xba, 0x42, 0x67,
	0x9b, 0x8a, 0x94, 0xb3, 0x5d, 0xab, 0xd8, 0x8d, 0x71, 0x7c, 0x47, 0x23, 0x96, 0xd0, 0x07, 0x35,
	0x86, 0x7c, 0xc4, 0xe2, 0x59, 0x38, 0x37, 0x6a, 0x7d, 0xcd, 0x3c, 0xc4, 0xd5, 0x19, 0x59, 0x50,
	0x13, 0xeb, 0x84, 0x1a, 0xf5, 0xbe, 0x66, 0x76, 0x86, 0xbd, 0xa7, 0xe7, 0x7b, 0xb3, 0x4e, 0x28,
	0x96, 0x71, 0xe8, 0x15, 0xd4, 0xbd, 0x88, 0xf9, 0x3f, 0x8c, 0x86, 0xcc, 0x7a, 0x54, 0x66, 0x75,
	0x72, 0x10, 0x2b, 0x0e, 0x99, 0xa0, 0x7b, 0x44, 0xf8, 0x0b, 0xca, 0x0d, 0xbd, 0x7f, 0x60, 0xb6,
	0x86, 0x9d, 0x4a, 0x57, 0xe2, 0xb8, 0xa4, 0x07, 0x33, 0xe8, 0x3c, 0x1c, 0xd8, 0x33, 0x16, 0xbd,
	0x81, 0x06, 0x17, 0x44, 0x64, 0x5c, 0xba, 0xd2, 0x19, 0x76, 0xca, 0xdc, 0xae, 0x44, 0x71, 0xc1,
	0x22, 0x04, 0xb5, 0x30, 0x9e, 0x31, 0xe9, 0x4b, 0x13, 0xcb, 0xff, 0x83, 0x0b, 0xa8, 0xcb, 0x94,
	0xe8, 0x0c, 0x6a, 0x29, 0x5d, 0xe5, 0x6b, 0x73, 0xf0, 0xf7, 0x7d, 0xc6, 0x32, 0x66, 0xf0, 0x53,
	0x2b, 0xe7, 0x57, 0x6c, 0xe5, 0x3f, 0x9a, 0xdf, 0x29, 0x34, 0xc4, 0x7d, 0x3c, 0x0d, 0x03, 0x39,
	0xbd, 0x26, 0xae, 0x8b, 0xfb, 0xf8, 0x73, 0x70, 0xf6, 0x01, 0x8e, 0x1f, 0x4d, 0x09, 0xb5, 0xe1,
	0x70, 0xfc, 0xf5, 0x76, 0x7c, 0x79, 0x75, 0x3d, 0xee, 0xee, 0xa1, 0x26, 0xd4, 0x9d, 0xcb, 0xab,
	0xd1, 0x97, 0xae, 0x86, 0x5a, 0xa0, 0x3b, 0x9f, 0x6e, 0x46, 0x93, 0xb1, 0xdb, 0xdd, 0x1f, 0x3a,
	0xa0, 0x8f, 0xd4, 0x43, 0x83, 0xde, 0x41, 0x2d, 0xff, 0xba, 0xd0, 0x7f, 0x1b, 0x2b, 0x36, 0x4f,
	0x4a, 0xef, 0x74, 0x07, 0x55, 0x43, 0x32, 0xb5, 0xb7, 0x9a, 0xf3, 0x0d, 0x5e, 0xb3, 0x74, 0x6e,
	0x2d, 0xd6, 0x09, 0x4d, 0x23, 0x1a, 0xcc, 0x69, 0x6a, 0xcd, 0x88, 0x97, 0x86, 0xbe, 0x7a, 0x9d,
	0x78, 0x79, 0xf3, 0xbb, 0x3d, 0x0f, 0xc5, 0x22, 0xf3, 0xf2, 0xfe, 0xec, 0xad, 0x68, 0x5b, 0x45,
	0x9f, 0xab, 0xe8, 0xf3, 0x39, 0xb3, 0x8b, 0x0b, 0x5e, 0x43, 0x42, 0x17, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x61, 0xf6, 0x0f, 0x15, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Step(ctx context.Context, opts ...grpc.CallOption) (Cluster_StepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cluster_serviceDesc.Streams[0], "/orderer.Cluster/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterStepClient{stream}
	return x, nil
}

type Cluster_StepClient interface {
	Send(*StepRequest) error
	Recv() (*StepResponse, error)
	grpc.ClientStream
}

type clusterStepClient struct {
	grpc.ClientStream
}

func (x *clusterStepClient) Send(m *StepRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterStepClient) Recv() (*StepResponse, error) {
	m := new(StepResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	// Step passes an implementation-specific message to another cluster member.
	Step(Cluster_StepServer) error
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct{}

func (*UnimplementedClusterServer) Step(srv Cluster_StepServer) error {
	return status.Errorf(codes.Unimplemented, "method Step not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Step(&clusterStepServer{stream})
}

type Cluster_StepServer interface {
	Send(*StepResponse) error
	Recv() (*StepRequest, error)
	grpc.ServerStream
}

type clusterStepServer struct {
	grpc.ServerStream
}

func (x *clusterStepServer) Send(m *StepResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterStepServer) Recv() (*StepRequest, error) {
	m := new(StepRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Step",
			Handler:       _Cluster_Step_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orderer/cluster.proto",
}
