// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_value.proto

package stateleveldb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBValue struct {
	Version              []byte   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBValue) Reset()         { *m = DBValue{} }
func (m *DBValue) String() string { return proto.CompactTextString(m) }
func (*DBValue) ProtoMessage()    {}
func (*DBValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f72618b1cd7c254, []int{0}
}

func (m *DBValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBValue.Unmarshal(m, b)
}

func (m *DBValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBValue.Marshal(b, m, deterministic)
}

func (m *DBValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBValue.Merge(m, src)
}

func (m *DBValue) XXX_Size() int {
	return xxx_messageInfo_DBValue.Size(m)
}

func (m *DBValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBValue proto.InternalMessageInfo

func (m *DBValue) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DBValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DBValue) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// DRUNIX: structure of MVCC in orderer
type DBMVCC struct {
	// storing version in leveldb
	Version              []byte   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	IsDelete             bool     `protobuf:"varint,2,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBMVCC) Reset()         { *m = DBMVCC{} }
func (m *DBMVCC) String() string { return proto.CompactTextString(m) }
func (*DBMVCC) ProtoMessage()    {}
func (*DBMVCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f72618b1cd7c254, []int{1}
}

func (m *DBMVCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBMVCC.Unmarshal(m, b)
}

func (m *DBMVCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBMVCC.Marshal(b, m, deterministic)
}

func (m *DBMVCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBMVCC.Merge(m, src)
}

func (m *DBMVCC) XXX_Size() int {
	return xxx_messageInfo_DBMVCC.Size(m)
}

func (m *DBMVCC) XXX_DiscardUnknown() {
	xxx_messageInfo_DBMVCC.DiscardUnknown(m)
}

var xxx_messageInfo_DBMVCC proto.InternalMessageInfo

func (m *DBMVCC) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DBMVCC) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func init() {
	proto.RegisterType((*DBValue)(nil), "stateleveldb.DBValue")
	proto.RegisterType((*DBMVCC)(nil), "stateleveldb.DBMVCC")
}

func init() { proto.RegisterFile("db_value.proto", fileDescriptor_1f72618b1cd7c254) }

var fileDescriptor_1f72618b1cd7c254 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x46, 0xf9, 0x15, 0xff, 0xd6, 0x50, 0x1c, 0x82, 0x43, 0xd0, 0x45, 0x3a, 0x39, 0x35, 0x83,
	0x0f, 0x20, 0xb4, 0x5d, 0x15, 0x29, 0xd8, 0xc1, 0xa5, 0x24, 0xcd, 0xb5, 0x0d, 0x26, 0xa6, 0x24,
	0xb7, 0x41, 0xdf, 0x5e, 0x4c, 0xab, 0x38, 0xb9, 0xdd, 0x73, 0x3f, 0x38, 0x70, 0xc8, 0x85, 0x92,
	0x43, 0x14, 0x66, 0x85, 0x6a, 0xf1, 0x0e, 0x1d, 0x2d, 0x02, 0x0a, 0x04, 0x03, 0x11, 0x8c, 0x92,
	0xe5, 0x33, 0xc9, 0xda, 0xba, 0xff, 0x9e, 0x29, 0x23, 0x59, 0x04, 0x1f, 0xb4, 0x7b, 0x67, 0x87,
	0x9b, 0xc3, 0x6d, 0xd1, 0xfd, 0x20, 0xbd, 0x24, 0x67, 0xc9, 0xc0, 0x4e, 0xd2, 0x7f, 0x03, 0x7a,
	0x45, 0x72, 0x0b, 0x28, 0x94, 0x40, 0xc1, 0x4e, 0xd3, 0xf0, 0xcb, 0xe5, 0x3d, 0x39, 0xb6, 0xf5,
	0x43, 0xdf, 0x34, 0xff, 0x58, 0xaf, 0xc9, 0xb9, 0x0e, 0x83, 0x02, 0x03, 0xb8, 0x99, 0xf3, 0x2e,
	0xd7, 0xa1, 0x4d, 0x5c, 0x3f, 0xbd, 0x3c, 0x4e, 0x1a, 0xe7, 0x55, 0x56, 0xa3, 0xb3, 0x7c, 0xfe,
	0x5c, 0xc0, 0x1b, 0x50, 0x13, 0x78, 0xfe, 0x2a, 0xa4, 0xd7, 0x23, 0x1f, 0x9d, 0x07, 0xbe, 0xbf,
	0xde, 0xe2, 0x7e, 0xe0, 0x87, 0x9d, 0x2c, 0xf2, 0x54, 0xa8, 0x24, 0xff, 0x5b, 0x2a, 0x8f, 0x29,
	0xff, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x60, 0xe8, 0x40, 0xd4, 0x10, 0x01, 0x00, 0x00,
}
